cometidoNacionales_get:
    path: /cometidosNacionales/{id}
    controller: App\Controller\CometidoNacionalesController::get
    methods:   [GET]

cometidoNacionales_getByRutAndEstado:
    path: /cometidosNacionales
    controller: App\Controller\CometidoNacionalesController::getByRutAndEstado
    methods:   [GET]
